<!DOCTYPE html>
<html lang="en"><head>
<script src="test_2_082025_files/libs/clipboard/clipboard.min.js"></script>
<script src="test_2_082025_files/libs/quarto-html/tabby.min.js"></script>
<script src="test_2_082025_files/libs/quarto-html/popper.min.js"></script>
<script src="test_2_082025_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="test_2_082025_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="test_2_082025_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="test_2_082025_files/libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.33">

  <meta name="author" content=" Lesley Chapman Hannah, Ph.D., M.S. College of Graduate Studies Northeast Ohio Medical University">
  <title>Estimation and Interpretation of Group Differences</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="test_2_082025_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="test_2_082025_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="test_2_082025_files/libs/revealjs/dist/theme/quarto-2c1b5f745a11cfad616ebade4a4a7d24.css">
  <link href="test_2_082025_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h2 style="color: #2A76DD;" class="title">Estimation and Interpretation of Group Differences</h2>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div style="font-size:20px;" class="quarto-title-author-name">
<br><br><span style="font-size:25px;"><strong>Lesley Chapman Hannah, Ph.D., M.S.</strong></span><br>College of Graduate Studies<br>Northeast Ohio Medical University 
</div>
</div>
</div>

</section>
<section class="slide level2">

<h3 id="from-single-group-estimation-to-comparative-estimation">From Single-Group Estimation to Comparative Estimation</h3>
<div style="font-size:0.63em">
<p>In the previous section, we discussed how estimation works for a single population quantity:</p>
<ul>
<li>point estimates for one mean or one proportion<br>
</li>
<li>sampling variability and standard error<br>
</li>
<li>confidence intervals for a single parameter</li>
</ul>
<p>In the current lecture we will focus on comparative estimation</p>
<blockquote>
<p>How different are two groups, and how should that difference be estimated and interpreted?</p>
</blockquote>
<p><strong>Biomedical examples</strong>: clinical trials, comparative effectiveness studies, and treatment evaluations are designed to estimate between-group effects</p>
</div>
</section>
<section class="slide level2">

<h3 id="estimation-for-comparing-groups">Estimation for Comparing Groups</h3>
<div style="font-size:0.66em">
<p>Central Goal: discuss statistical estimation for group comparisons</p>
<p>Discuss the following comparative estimands:</p>
<ul>
<li>difference in sample means for a continuous outcome<br>
</li>
<li>risk difference for a binary outcome<br>
</li>
<li>risk ratio for a binary outcome<br>
</li>
<li>odds and odds ratios for a binary outcome</li>
</ul>
<p>Each comparative estimand follows the same general framework:</p>
<ul>
<li>estimate the outcome within each group<br>
</li>
<li>compare groups on an interpretable scale<br>
</li>
<li>use confidence intervals to judge both magnitude and precision</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="review-statistical-estimation">Review: Statistical Estimation</h3>
<div style="font-size:0.66em">
<ul>
<li><p>statistical estimation involves turning observed sample data into evidence about an unknown population quantity</p></li>
<li><p>for estimand comparisons, estimation answers a question like this:</p></li>
</ul>
<blockquote>
<p>based on the differences observed in the study sample, what is the best estimate of the corresponding treatment effect in the population?</p>
</blockquote>
<p>Process inovlves the following:</p>
<ol type="1">
<li>define the population quantity of interest<br>
</li>
<li>calculate a sample-based quantity that targets it<br>
</li>
<li>interpret that quantity as an estimate of the underlying effect</li>
</ol>
</div>
</section>
<section class="slide level2">

<h3 id="estimating-differences-between-groups">Estimating Differences Between Groups</h3>
<div style="font-size:0.6em">
<ul>
<li><p>goal is to understand how two groups differ:</p></li>
<li><p>treatment vs control<br>
</p></li>
<li><p>exposed vs unexposed<br>
</p></li>
<li><p>biomarker-positive vs biomarker-negative</p></li>
</ul>
<p>We are now estimating:</p>
<blockquote>
<p>a contrast between two population quantities</p>
</blockquote>
</div>
</section>
<section class="slide level2">

<h3 id="defining-the-estimand-in-group-comparisons">Defining the Estimand in Group Comparisons</h3>
<div style="font-size:0.66em">
<p>Review:</p>
<ul>
<li><p><strong>estimand [what we want to learn]</strong> : population quantity we aim to learn about</p></li>
<li><p><strong>estimator [method used to estimate target]</strong>: rule or formula used to approximate the estimand using sample data</p></li>
</ul>
<p>In a two-group comparison, the estimand shows the relationship between two population quantities, such as:</p>
<ul>
<li>difference in population means<br>
</li>
<li>difference in population probabilities<br>
</li>
<li>ratio of population probabilities<br>
</li>
<li>ratio of population odds</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="defining-how-groups-differ-multiple-comparative-measures">Defining How Groups Differ: Multiple Comparative Measures</h3>
<div style="font-size:0.66em">
<p>In a two-group study, the data provide:</p>
<ul>
<li>an outcome in the treatment group<br>
</li>
<li>an outcome in the control group</li>
</ul>
<p>From these, we can estimate <strong>how the groups differ</strong></p>
<p>But there is not just one way to define that difference.</p>
<p>Differences between groups [treatment effect] can be framed as:</p>
<ul>
<li><strong>absolute change</strong> in outcome<br>
</li>
<li><strong>relative change</strong> in outcome<br>
</li>
<li>comparison of <strong>event vs non-event likelihood</strong></li>
</ul>
<p>Each of which defines a different population quantity [estimand] that the study is trying to estimate</p>
</div>
</section>
<section class="slide level2">

<h3 id="defining-how-groups-differ-multiple-comparative-measures-1">Defining How Groups Differ: Multiple Comparative Measures</h3>
<div style="font-size:0.66em">
<p>Multiple comparative measures can exist within a study:</p>
<ul>
<li><strong>mean difference</strong> → estimates difference in population averages<br>
</li>
<li><strong>risk difference</strong> → estimates absolute difference in probabilities<br>
</li>
<li><strong>risk ratio</strong> → estimates relative difference in probabilities</li>
<li><strong>odds ratio</strong> → estimates difference on the odds scale</li>
</ul>
<p>What changes is:</p>
<blockquote>
<p><strong>the question we are asking about how the groups differ in the population</strong></p>
</blockquote>
</div>
</section>
<section id="the-structure-of-all-comparative-estimators" class="slide level2">
<h2>The Structure of All Comparative Estimators</h2>
<div style="font-size:0.66em">
<p>comparative measures follow a similar estimation structure:</p>
<ol type="1">
<li>estimate the outcome in each group<br>
</li>
<li>combine those estimates into a comparison<br>
</li>
<li>interpret that comparison as a population effect</li>
</ol>
</div>
</section>
<section class="slide level2">

<h3 id="mean-difference">Mean Difference</h3>
<p><span class="math display">\[
\widehat{\Delta} = \bar{x}_1 - \bar{x}_0
\]</span></p>
<div style="font-size:0.66em">
<p>Mean Difference:</p>
<ul>
<li><p><strong>mean difference</strong> is the difference between the average outcome in two groups.</p></li>
<li><p><span class="math inline">\(\bar{x}_1\)</span>: sample mean in the treatment group<br>
</p></li>
<li><p><span class="math inline">\(\bar{x}_0\)</span>: sample mean in the control group</p></li>
</ul>
<p>quantity is used to estimate the corresponding population mean difference:<span class="math inline">\(\mu_1 - \mu_0\)</span> - true difference in average outcome between the two groups in the full population</p>
<p>estimator of the population mean difference: <span class="math inline">\(\mu_1 - \mu_0\)</span></p>
</div>
</section>
<section class="slide level2">

<h3 id="risk-difference">Risk Difference</h3>
<p><span class="math display">\[
\widehat{RD} = \hat{p}_1 - \hat{p}_0
\]</span></p>
<div style="font-size:0.6em">
<p><strong>risk difference</strong> : sample-based estimate of the true absolute difference in event probability between groups in the population</p>
<p>For a binary outcome, each group has a population event probability:</p>
<ul>
<li><span class="math inline">\(p_1\)</span>: true probability of the event in the treatment group population<br>
</li>
<li><span class="math inline">\(p_0\)</span>: true probability of the event in the control group population</li>
</ul>
<p>study provides sample-based estimates because the population probabilities are unknown because the full population is not observed:</p>
<ul>
<li><span class="math inline">\(\hat{p}_1\)</span>: observed event proportion in the treatment group<br>
</li>
<li><span class="math inline">\(\hat{p}_0\)</span>: observed event proportion in the control group</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="risk-difference-1">Risk Difference</h3>
<p><span class="math display">\[
\widehat{RD} = \hat{p}_1 - \hat{p}_0
\]</span></p>
<div style="font-size:0.6em">
<p><strong>Risk difference</strong> compares these two probabilities and asks:</p>
<blockquote>
<p>how many probability units apart are the groups?</p>
</blockquote>
<p>Therefore</p>
<p><span class="math display">\[
\widehat{RD} = \hat{p}_1 - \hat{p}_0
\]</span></p>
<p>is used to estimate:</p>
<blockquote>
<p><span class="math inline">\(RD = p_1 - p_0\)</span></p>
</blockquote>
<p>the true <strong>difference in event probability</strong> between treatment and control in the population</p>
</div>
</section>
<section class="slide level2">

<h3 id="risk-difference-2">Risk Difference</h3>
<div style="font-size:0.6em">
<p>Example:</p>
<p>Consider a clinical trial comparing a new therapy to standard care, where the outcome is <strong>treatment response</strong> (yes/no)</p>
<p>Suppose the observed response probabilities in the sample are:</p>
<ul>
<li>treatment group: <span class="math inline">\(\hat{p}_1 = 0.62\)</span><br>
</li>
<li>control group: <span class="math inline">\(\hat{p}_0 = 0.48\)</span></li>
</ul>
<p>if the treatment response probability is 0.62 and the control response probability is 0.48, then the estimand risk difference is:</p>
<p><span class="math display">\[
\widehat{RD} = 0.62 - 0.48 = 0.14
\]</span></p>
<p>Interpretation: there is an estimated <strong>14 percentage-point increase</strong> in response probability under treatment</p>
</div>
</section>
<section class="slide level2">

<h3 id="risk-ratio">Risk Ratio</h3>
<p><span class="math display">\[
\widehat{RR} = \frac{\hat{p}_1}{\hat{p}_0}
\]</span></p>
<div style="font-size:0.66em">
<p>risk ratio :</p>
<ul>
<li>estimator of the population relative risk</li>
<li>quantifies how many times larger [or smaller] the outcome probability is in one group compared to another</li>
</ul>
<p>risk ratio compares two estimated probabilities:</p>
<ul>
<li><p><strong>numerator</strong>: <span class="math inline">\(\hat{p}_1\)</span><br>
→ outcome probability for the treatment group → e.x.: estimated probability of the outcome in the <strong>treatment group</strong></p></li>
<li><p><strong>denominator</strong>: <span class="math inline">\(\hat{p}_0\)</span><br>
→ outcome probability for the control group → e.x.: estimated probability of the outcome in the <strong>control group</strong></p></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="risk-ratio-1">Risk Ratio</h3>
<p><span class="math display">\[
\widehat{RR} = \frac{\hat{p}_1}{\hat{p}_0}
\]</span></p>
<div style="font-size:0.66em">
<p>Question:</p>
<blockquote>
<p>how many times as likely is the outcome in the treatment group compared to the control group?</p>
</blockquote>
<p><strong>Interpretation</strong></p>
<ul>
<li><span class="math inline">\(\widehat{RR} = 1\)</span> → equal probabilities<br>
</li>
<li><span class="math inline">\(\widehat{RR} &gt; 1\)</span> → outcome more likely in treatment<br>
</li>
<li><span class="math inline">\(\widehat{RR} &lt; 1\)</span> → outcome less likely in treatment<br>
</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="odds-and-odds-ratio">Odds and Odds Ratio</h3>
<p><span class="math display">\[
\widehat{OR} = \frac{\hat{p}_1/(1-\hat{p}_1)}{\hat{p}_0/(1-\hat{p}_0)}
\]</span></p>
<div style="font-size:0.6em">
<p><strong>odds ratio</strong></p>
<ul>
<li>metric measures the association between two groups by comparing their odds</li>
<li>sample-based estimate of how the odds of an outcome differ between groups in the population [expressed on an odds scale]</li>
</ul>
<p>Note:</p>
<ul>
<li>probabilities describe frequency of events<br>
</li>
<li>odds describe event relative to non-event</li>
</ul>
<p><strong>Important distinction</strong></p>
<ul>
<li><strong>probability</strong> (<span class="math inline">\(p\)</span>): proportion of individuals who experience the event<br>
</li>
<li><strong>odds</strong> (<span class="math inline">\(p/(1-p)\)</span>): ratio of event probability to non-event probability</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="comparing-groups-using-different-measures">Comparing Groups Using Different Measures</h3>
<div style="font-size:0.66em">
<p>Each measure estimates a different type of population comparision between groups, and answer:</p>
<blockquote>
<p>how do outcomes differ between groups in the population?</p>
</blockquote>
<p>Where:</p>
<ul>
<li>Mean difference → difference in averages<br>
</li>
<li>Risk difference → difference in probabilities<br>
</li>
<li>Risk ratio → relative probability<br>
</li>
<li>Odds ratio → relative odds</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="clinical-trial-context-defining-the-treatment-effect">Clinical Trial Context: Defining the Treatment Effect</h3>
<div style="font-size:0.63em">
<p>Consider a randomized clinical study evaluating a <strong>new therapy</strong> compared to <strong>standard care</strong></p>
<p>Study Goal: estimate how the treatment changes those outcomes in the target population</p>
<p>Key outcomes of interest include:</p>
<ul>
<li><strong>Clinical response</strong> [binary]: did the patient respond to treatment?<br>
</li>
<li><strong>Serious adverse events</strong> [binary]: did the patient experience a harmful event?<br>
</li>
<li><strong>Change in kidney function (eGFR)</strong> [continuous]: how much did kidney function improve or decline?</li>
</ul>
<p><strong>Connection to estimation</strong></p>
<ul>
<li><p>outcomes are measured on different scales, the treatment effect must be defined and estimated differently:</p></li>
<li><p><strong>mean difference</strong> : estimates difference in average eGFR change<br>
</p></li>
<li><p><strong>risk difference</strong> : estimates absolute difference in probability (response or adverse event)<br>
</p></li>
<li><p><strong>risk ratio</strong> : estimates relative difference in probability<br>
</p></li>
<li><p><strong>odds ratio</strong> : estimates difference on the odds scale</p></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="dataset-overview">Dataset Overview</h3>
<div style="font-size:0.6em">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
     id treatment   response serious_ae egfr_change   age   bmi
  &lt;int&gt; &lt;chr&gt;          &lt;int&gt;      &lt;int&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1 New therapy        0          0      11.4      60  24.4
2     2 New therapy        1          0      10.3      70  21.1
3     3 New therapy        1          0      -0.276    63  27.2
4     4 New therapy        1          0      -7.38     38  18.3
5     5 New therapy        1          0       8.88     58  34.9
6     6 New therapy        1          0      -5.93     73  26.5</code></pre>
</div>
</div>
<ul>
<li><p>each row represents one trial participant</p></li>
<li><p><code>treatment</code> : identifies the treatment arm<br>
</p></li>
<li><p><code>response</code> : coded 1 for clinical response and 0 for no response<br>
</p></li>
<li><p><code>serious_ae</code> : coded 1 for a serious adverse event and 0 for none<br>
</p></li>
<li><p><code>egfr_change</code> : change in estimated glomerular filtration rate from baseline to follow-up</p></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="difference-in-sample-means">Difference in Sample Means</h3>
<div style="font-size:0.6em">
<p><span class="math display">\[
\widehat{\Delta} = \bar{x}_1 - \bar{x}_0
\]</span></p>
<p>estimated mean difference between two groups</p>
<ul>
<li><span class="math inline">\(\widehat{\Delta}\)</span> : estimated population mean difference<br>

<ul>
<li>difference in eGFR change&nbsp;</li>
</ul></li>
<li><span class="math inline">\(\bar{x}_1\)</span> : sample mean in group 1<br>

<ul>
<li>sample mean eGFR change in the <strong>new therapy group</strong><br>
</li>
</ul></li>
<li><span class="math inline">\(\bar{x}_0\)</span> : sample mean in group 0<br>

<ul>
<li>sample mean eGFR change in the <strong>standard care group</strong></li>
</ul></li>
<li>positive value : average outcome is higher in group 1<br>
</li>
<li>negative value : average outcome is lower in group 1</li>
</ul>
<p>estimated difference in <strong>average change in eGFR</strong> between treatment groups</p>
<p>Measure compares:</p>
<blockquote>
<p>average change in kidney function for patients receiving the new therapy<br>
vs<br>
average change in kidney function for patients receiving standard care</p>
</blockquote>
</div>
</section>
<section class="slide level2">

<h3 id="group-means-for-egfr-change">Group Means for eGFR Change</h3>
<div style="font-size:0.6em">
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a>egfr_summary <span class="ot">&lt;-</span> trial_df <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href=""></a>  <span class="fu">group_by</span>(treatment) <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href=""></a>  <span class="fu">summarise</span>(</span>
<span id="cb2-4"><a href=""></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb2-5"><a href=""></a>    <span class="at">mean_egfr_change =</span> <span class="fu">mean</span>(egfr_change),</span>
<span id="cb2-6"><a href=""></a>    <span class="at">sd_egfr_change =</span> <span class="fu">sd</span>(egfr_change)</span>
<span id="cb2-7"><a href=""></a>  )</span>
<span id="cb2-8"><a href=""></a></span>
<span id="cb2-9"><a href=""></a>egfr_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  treatment         n mean_egfr_change sd_egfr_change
  &lt;chr&gt;         &lt;int&gt;            &lt;dbl&gt;          &lt;dbl&gt;
1 New therapy     220             5.65           9.44
2 Standard care   220             1.01           9.85</code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p><strong>Average outcome within a treatment group</strong></p>
<p>→ on average, patients receiving the new therapy improved by <strong>5.65 eGFR units</strong> → on average, patients receiving standard care improved by <strong>1.01 eGFR units</strong></p>
<p><strong>Estimated treatment effect</strong></p>
<p><span class="math display">\[
\widehat{\Delta}=5.65−1.01=4.64
\]</span> Estimated difference in average kidney-function change between trial arms:</p>
<ul>
<li>patients receiving the new therapy improved <strong>4.64 eGFR units</strong> more than patients receiving standard care</li>
<li>positive value means the new-therapy group had a larger average improvement than standard care</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="plot-of-mean-egfr-change-by-group">Plot of Mean eGFR Change by Group</h3>
<div style="font-size:0.6em">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="test_2_082025_files/figure-revealjs/unnamed-chunk-3-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>New therapy group</p>
<ul>
<li>mean increase in eGFR is higher (around ~5–6 units)<br>
</li>
<li>confidence interval is entirely above zero<br>

<ul>
<li>results suggests a consistent improvement in kidney function</li>
</ul></li>
</ul>
<p>Standard care group</p>
<ul>
<li>mean change is smaller (around ~1 unit)<br>
</li>
<li>confidence interval is wider and appears to include values near or slightly below zero<br>

<ul>
<li>results suggests greater uncertainty and likely little to no improvement</li>
</ul></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="estimated-risk-difference-for-clinical-response">Estimated Risk Difference for Clinical Response</h3>
<div style="font-size:0.6em">
<p>Goal: find the difference in response probabilities between the two treatment groups</p>
<p><span class="math display">\[
\hat{p}_{new}−\hat{p}_{standard}
\]</span></p>
<p><em>{new}: proportion of patients who responded under the new therapy </em>{standard}: proportion who responded under standard care</p>
<blockquote>
<p>How much does the probability of clinical response change between the two groups?</p>
</blockquote>
<p>positive value → higher response probability under the new therapy negative value → lower response probability under the new therapy value near zero → little or no difference between groups</p>
</div>
</section>
<section class="slide level2">

<h3 id="estimated-risk-difference-for-clinical-response-1">Estimated Risk Difference for Clinical Response</h3>
<div style="font-size:0.6em">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  treatment         n responses nonresponses  risk
  &lt;chr&gt;         &lt;int&gt;     &lt;int&gt;        &lt;int&gt; &lt;dbl&gt;
1 New therapy     220       161           59 0.732
2 Standard care   220       109          111 0.495</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2363636</code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>New therapy risk = 0.732 → 73.2% of patients responded</p>
<p>Standard care risk = 0.495 → 49.5% of patients responded</p>
<dl>
<dt>Out of 100 patients:</dt>
<dd>
<p>73 would respond under the new therapy</p>
</dd>
<dd>
50 would respond under standard care
</dd>
</dl>
<p>Risk Difference: <span class="math inline">\(0.732−0.495=0.236\)</span></p>
<p>probability of clinical response is 23.6 percentage points higher under the new therapy compared to standard care</p>
</div>
</section>
<section class="slide level2">

<h3 id="estimated-risk-ratio-for-clinical-response">Estimated Risk Ratio for Clinical Response</h3>
<div style="font-size:0.6em">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.477064</code></pre>
</div>
</div>
<p>risk ratio compares the response probabilities between the two groups</p>
<p><span class="math display">\[
\frac{\hat{p}_{\text{new}}}{\hat{p}_{\text{standard}}}
\]</span> <em>{new}: response probability under the new therapy </em>{standard}: response probability under standard care</p>
<p><span class="math display">\[
\frac{0.732}{0.495}}=1.48
\]</span> - patients receiving the new therapy are about 1.48 times as likely to respond as those receiving standard care - risk difference [0.236] → response is 23.6 percentage points higher - risk ratio [1.48] → response is 48% higher relative to standard care</p>
</div>
</section>
<section class="slide level2">

<h3 id="odds-of-response-in-each-group">Odds of Response in Each Group</h3>
<div style="font-size:0.6em">
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a>response_odds <span class="ot">&lt;-</span> response_summary <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">odds =</span> risk <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> risk))</span>
<span id="cb7-3"><a href=""></a></span>
<span id="cb7-4"><a href=""></a>response_odds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  treatment         n responses nonresponses  risk  odds
  &lt;chr&gt;         &lt;int&gt;     &lt;int&gt;        &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
1 New therapy     220       161           59 0.732 2.73 
2 Standard care   220       109          111 0.495 0.982</code></pre>
</div>
</div>
<blockquote>
<p>How do the odds of response compare between the two groups?</p>
</blockquote>
<p><strong>Interpretation</strong></p>
<p><span class="math display">\[
odds = \frac{p}{1-p}
\]</span></p>
<p>Where:</p>
<p><strong>p</strong>: probability of response <strong>1−p</strong>: probability of no response</p>
<p>New therapy [odds = 2.73] - odds of response are ~ 2.7 - response is much more likely than non-response</p>
<p>Standard care [odds = 0.98] - odds are about 1 - response and non-response are likely to occur at similar rates</p>
</div>
</section>
<section class="slide level2">

<h3 id="estimated-odds-ratio-for-clinical-response">Estimated Odds Ratio for Clinical Response</h3>
<div style="font-size:0.6em">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.778884</code></pre>
</div>
</div>
<p>Goal: estimate the relative odds of response under the new therapy compared with standard care</p>
<p>Interpretation: odds of clinical response are approximately 2.78 times higher under the new therapy compared to standard care</p>
</div>
</section>
<section class="slide level2">

<h3 id="summary">Summary</h3>
<div style="font-size:0.6em">
<ul>
<li>discussed different metrics used to estimate how outcomes differ between groups in the population</li>
</ul>
<p>Comparative estimation follows a common structure:</p>
<ol type="1">
<li>estimate the outcome within each group</li>
<li>combine those estimates into a comparison</li>
<li>interpret the result as a population effect</li>
</ol>
<p>Key measures:</p>
<ul>
<li>mean difference → difference in averages (continuous outcomes)</li>
<li>risk difference → absolute difference in probabilities</li>
<li>risk ratio → relative difference in probabilities</li>
<li>odds ratio → relative difference on the odds scale</li>
</ul>
</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="test_2_082025_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="test_2_082025_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="test_2_082025_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>